Code refactoring
MrPoofPoof/LaserFile-reminder pull request #1
Opened 2023-06-06 13:32 UTC by MrPoofPoof

2023-06-06 13:50 UTC, KFrydryk requested changes

2023-06-06 13:50 UTC, KFrydryk commented on TimerGUI.pyw
> +import tkinter as tk, time, math
Place imports on top of the file, before defining any constants/variables

2023-06-06 13:50 UTC, KFrydryk commented on TimerGUI.pyw
> +    isLoggerOn = createLabel(initialWindow, 'Czy włączono logger lasera?')
In python strings are generally used with double quotes for text, and single quotes for identifiers/paths. No functional difference, just good practice.

2023-06-06 13:50 UTC, KFrydryk commented on TimerGUI.pyw
> -        justify='center',
i.e. this is a proper use of single quoted string

2023-06-06 13:50 UTC, KFrydryk commented on TimerGUI.pyw
> +    timerStartButton = createButton(initialWindow, f'TAK +{round((timerDelay/3600))}h', 'light green', timerStart)
Try `"TAK +{time}h".format(time=round((timerDelay/3600)))` for better readability

2023-06-06 13:50 UTC, KFrydryk commented on TimerGUI.pyw
> +    shortWindowHideButton = createButton(initialWindow, f'NIE +{round((shortHideButtonDelay/60))}min', 'red', shortWindowHide)
ditto

2023-06-06 13:50 UTC, KFrydryk commented on TimerGUI.pyw
> +    changeLog = createLabel(recurringWindow, 'ZMIEŃ LOG LASERA \n(nie nad linią!)')
ditto

2023-06-06 13:50 UTC, KFrydryk commented on TimerGUI.pyw
>      windowHeight = 122
Might be worth to pass width, height and position in a structure as parameter for a generic `createWindow` method

2023-06-06 13:51 UTC, KFrydryk commented
Also, drop the "Minor change" and "revert" commits

2023-06-06 14:07 UTC, MrPoofPoof commented on TimerGUI.pyw
> +import tkinter as tk, time, math
Done

2023-06-07 08:29 UTC, KFrydryk approved these changes
LGTM

2023-06-07 08:30 UTC, merged